sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7-dev'
install: pip install tox-travis codecov
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  user: kandziu
  password:
    secure: Iz7EwULuRWm66lTGdNnvyEQXErOv7ZGRgzYcaX0F0a7nGmjVjEIrEtBf5PvY7vxbu2hcXRgOjF5p5VCNPFICF8zUvB5fdjleuhZt1z4eGuD716VJlVjWyYi/pa66WeCi3220Tsj9uqKu/U7CdbFHG9RntIbYjQRmXh9iGja8UNwqus0fvdnk/diO/tTzpeSh0XfjTgOjhWNP+gckrJLbw+qFhuppE8TRIcnfnpu+jv4rN2FwhpGLd2QTshmYqqusrPgoOfEXApnUi+AY2YOvGnj+pmO9G333UI3qIwu2ga4EHq8NdC6kNSks1PkBw5UkowU5Etv0r4rgDoanDLRhFThiSqgE/M/HLi03p4tpZO1Eu/zWQdRkIdwwDYoLLGBEopZR5RvqhNStFXKL5sidmF7lAIvfcgDM2E8/pi+EcUUlxKoZ9HHxlRrhgCHx8DZrZnAM0EsSnZ+fsbuzLNdFZxEway1Q9I+vefiOOMFo4fu0wTGYN3T/UfD25HgdFqp8GtZZgw1YMqwCQplpeRRHbmEzBU/+IQNVtl7LXkvGo5IWjtzGXCbo0byzalKxfn3WnCDLGT4J+9Mh+nXoJrq/UXpJ5q1jf4wn1971Gh1p/oQVj6sZDPwDqh05wfwHfUfM5m7lh9R+w7JzqTVVlbXVh0MzmYmBVs8+O6B/b+0hPCA=
  on:
    tags: true