sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- 3.7-dev
install: pip install tox-travis codecov
script: tox
after_success:
- codecov
deploy:
  password:
    secure: oSu1fShOShWiwL4rfwiqaYpJzfI+vuzLOJHWLA6Ztnm5bY+vWljB3kzC6T5P2mQpibOBHz3c0yhjulcCHiJbj2IU2oerS2a+0QjFGsRzeP439ofQhd53qKuFL7Jo9nMjr6O9ylICY/g02eQMdzQ8DN46FCMR5vlYbmBzuV7+TA+kLJJNMfgRDlzgLemHeV6wLbsAw6Diz6lRhLc6pCDChBlI9xATCRflS9m54BAt13E1Yant9YIkXM51G61FSZIoQMgZ6I84Xjk9O5wRrnrXbeIhA83mrluQ4HnQVwPbrfLuUn4ADd4bKNIVfmXwMBbSxhuwmWe3MpnDbRsVQsszDP3Po6UhG5tAa4dnXsyXfRS/u4x6G28Rx+y39bfRiCu6pp94NcTcvCoBAyZt0NRyVr6SD3PmQX1sqwOIL1GcvT4BLWfeOlU2c9b0o3yJL2Ik9lLHa6cryrr/bdRayIl2xMFVCfi03X4PzctFd2TPO/cyKojLIva0T6kigtSQBaN/OXDKIStBRoFjCik1zkShLDMqFe+wot8JmNq9WF9Wfc/ejnaw9jLhKfEP43C4P3TMIzysm160Uy274RYLc8S1ei1Nr5uqp/Vsvm5xz9UMFulwCuEsfODFg/jHa6Lyn7trPaSFSPVHN5++umPQpRGdxXCEmznaG9gD20ZBniQTG7U=
