sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7-dev'
install: pip install tox-travis codecov
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  user: kandziu
  twine_version: 1.12.1
  password:
    secure: k53AsLqIAUzRsMIXmi/V6rGA9B+kQ4eLkc5QaDtIWEujIC2x9bygGbxNXjmBUyTcQ0AynEmuTmRuO6RV8ldPlRdfKG+lhtP7nkUvmnk1RzwSB/g/Suikvn/ahi6/AoisWvH1ZGO0AienbWxaqdXgBhGJAaaFI1VcBqP6d2sALDrKERW8/Te225tFKCDpQJ1dDQHdYjodTf3VRDcpp7ZAyB25AlcSknW/f+Hrxt3hY1LU1jKgob3oABOOxX5H3AF7PcEH1ptPljajBZRK4/NrJBBJQlbVs6SAUAqcp8GFn6L8cbWq45Iz8H65UvbX4KQiqwPiNdZw5fAXScQVk33tO+yFMo+ZfHN52enC20ycoYO4XimrHvcjLsOmAV1BWcZ2IUBvMhaOxxzTHxezPpKCJSanotgRkVv6Q8e0XJCVD3ylOVwgkp+1OBTRacmdB7JtrbAobbzOEVxoVCHRHMk3LA2D/sIn/FxdaE65TNEqBaSDnFMFewAxg5sldyCQFRbJgvMA800hgNtb68zEBfU1xn0Hw/5P6APf7myEcJvL4XB2BM21pvis5MoOYArjiisDUQyl5e88qa68lS3LfyjWdvktazVFjTUj2pdZ1832hWePYhf0Zzjp42ff1kikWUs55FEMlSx4U5GnkR+eQxXgP8zMncmo5Pkqb7tHkj77kKc=
  on:
    tags: true